# Generated by Django 4.1.3 on 2022-11-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_typed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_music', models.CharField(max_length=50)),
                ('music', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Musica de fundo',
            },
        ),
    ]
