# Generated by Django 4.1.3 on 2022-11-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('img_default', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Imagem padrão',
            },
        ),
    ]
